name: palette
description: >-
  A package for creating, generating, and interfacing with color palettes.
  With support for the CMYK, HSI, HSL, HSP, HSB, LAB, Oklab, RGB, and XYZ
  color spaces.
version: 1.1.0+1
homepage: https://github.com/james-alex/palette

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  color_models: ^1.2.1
  num_utilities: ^1.0.1
  unique_list: ^1.0.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
