name: flutter_palette
description: >-
  A package for creating, generating, and interfacing with color palettes.
  With support for the CMYK, HSI, HSL, HSP, HSB, LAB, Oklab, RGB, and XYZ
  color spaces.
version: 1.0.0+2
homepage: https://github.com/james-alex/palette

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_color_models: ^1.2.0
  palette: ^1.0.0+2
  unique_list: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
